Peninsula-Pirate-Pawns/PPP-RubyRooks

- Gemfile
- Gemfile.lock
- app/assets/javascripts/games.coffee
- app/assets/stylesheets/games.scss
- app/controllers/games_controller.rb
- app/helpers/games_helper.rb
- app/models/game.rb
- app/views/games/new.html.erb
- app/views/games/show.html.erb
- config/database.yml
- config/initializers/simple_form.rb
- config/initializers/simple_form_bootstrap.rb
- config/locales/simple_form.en.yml
- config/routes.rb
- db/migrate/20191213143617_create_games.rb
- db/schema.rb
- lib/templates/erb/scaffold/_form.html.erb
- test/controllers/games_controller_test.rb
- test/fixtures/games.yml
- test/models/game_test.rb
Fixes https://github.com/Peninsula-Pirate-Pawns/PPP-RubyRooks/issues/1
> Add crud simpleform

- Gemfile
- Gemfile.lock
Fixes [#11] https://github.com/Peninsula-Pirate-Pawns/PPP-RubyRooks/issues/11
> Add Rubocop Gem

- .circleci/config.yml
- .gitignore
- config/database.yml
- db/schema.rb
This needs to be merged before I can test to see if CircleCI integration is working.
> Add circleci

- Gemfile
- Gemfile.lock
- app/controllers/callbacks_controller.rb
- app/models/user.rb
- config/initializers/devise.rb
- spec/controllers/callbacks_controller_spec.rb
> Add omniauth twitter

- app/controllers/static_pages_controller.rb
- app/models/bishop.rb
- app/models/game.rb
- app/models/king.rb
- app/models/knight.rb
- app/models/pawn.rb
- app/models/piece.rb
- app/models/position.rb
- app/models/queen.rb
- app/models/rook.rb
- db/migrate/20191219012618_create_pieces.rb
- db/migrate/20191219012749_add_type_to_piece.rb
- db/migrate/20191219142956_add_game_id_to_games.rb
- db/migrate/20191220011751_remove_game_id_from_games.rb
- db/migrate/20191220012257_remove_game_id_from_pieces.rb
- db/migrate/20191220023114_add_game_id_to_piece.rb
- db/migrate/20191220143322_remove_pieces_table_and_rename_positions_table.rb
- db/schema.rb
- spec/factories.rb
- spec/factorybot_spec.rb
- spec/models/bishop_spec.rb
- spec/models/game_spec.rb
- spec/models/king_spec.rb
- spec/models/knight_spec.rb
- spec/models/pawn_spec.rb
- spec/models/piece_spec.rb
- spec/models/position_spec.rb
- spec/models/queen_spec.rb
- spec/models/rook_spec.rb
- spec/spec_helper.rb
This PR will add a **Piece model** which will be the the **S**ingle **T**able which all the **Pieces (pawn, rook, bishop knight, queen, king)** will **I**nherit from. 
The lines being removed from **spec_helper.rb** were a configuration I had added for **CircleCI** that we do not need (it was preventing **byebug** from outputting to the terminal, so I removed it).
> Add piece model

- app/assets/stylesheets/master.scss
- app/controllers/games_controller.rb
- app/models/game.rb
- app/views/games/show.html.erb
- app/views/layouts/application.html.erb
- db/migrate/20191220023114_add_game_id_to_piece.rb
- db/migrate/20191220162820_remove_first_move_id_in_games.rb
- db/migrate/20191220163146_add_first_move_to_games.rb
- db/migrate/20191220164556_remove_creating_user_id_in_games.rb
- db/migrate/20191220165049_remove_winner_and_invited_user_add_references_for_winner_creating_user_and_invited_user_to_games.rb
- db/schema.rb
- spec/factories.rb
- spec/models/game_spec.rb
- spec/models/piece_spec.rb
Howdy all okay second try at this. The tests all now pass but this might be an issue later on because the tests are requiring that there be a winner even though we would not create a game with a winner already. A picture of the board. It changes size with the size of the viewing window.
> Chessboard

- app/models/game.rb
- db/schema.rb
Fixes https://github.com/Peninsula-Pirate-Pawns/PPP-RubyRooks/issues/27
> Add scope gameavailable

- app/controllers/games_controller.rb
- app/models/game.rb
- app/views/games/index.html.erb
- app/views/games/show.html.erb
- app/views/static_pages/index.html.erb
- config/routes.rb
- db/migrate/20191221191438_add_omniauth_to_users.rb
- db/schema.rb
This PR allows users to join available games. Also lists out all games the user is part of.
> Add games update action

- app/models/piece.rb
Fixes [#30] https://github.com/Peninsula-Pirate-Pawns/PPP-RubyRooks/issues/30
> Create Is Obstructed Method

- app/controllers/games_controller.rb
- app/models/game.rb
- app/views/games/index.html.erb
- app/views/games/show.html.erb
- spec/controllers/games_controller_spec.rb
- spec/factories.rb
- spec/factorybot_spec.rb
- spec/models/game_spec.rb
- spec/rails_helper.rb
Fix #36. I also did some slight styling to the index page. Headlines only show up if games exist to display. I added comments for the other changes. Nothing large.
> Populate a game

- app/models/piece.rb
- db/schema.rb
- spec/models/piece_spec.rb
The biggest changes here are the tests for the Piece model. I used a before(:each) block to clean up the tests and also added a few tests to cover all scenarios for the move_to! method. 
Eurus and I wrote out the code for the move_to! method the other day, but I refactored it slightly and added a flash message for when a move is invalid. 
Happy new decade!
> Add move_to! Piece method and tests

- app/models/piece.rb
- db/schema.rb
- spec/controllers/pieces_controller_spec.rb
- spec/models/piece_spec.rb
Made some changes to the controller test so it is only testing the piece#update action. 
Refactored the piece model tests to be simpler and more straight-forward (thanks to piece.reload).
> Update piece controller spec

- app/controllers/games_controller.rb
- app/models/game.rb
- db/schema.rb
- spec/controllers/games_controller_spec.rb
player_one and player_two are now randomly assigned when invited_user joins a game. I think this may also fix the twitter issue. Shane might have to confirm I do not have twitter.
> Assign players

- spec/controllers/pieces_controller_spec.rb
Just a small little update to expand the number of tests for the p`pieces#update` controller.
> More tests for updating a pieces position

- app/models/knight.rb
- db/migrate/20200102030405_add_type_to_piece.rb
- db/schema.rb
- spec/factories.rb
- spec/models/knight_spec.rb
This adds a method in knight.rb to check a moves validity as well as some rspec tests to back up that method.
> Add knight valid_move? method with specs

- app/models/queen.rb
- spec/factories.rb
- spec/models/queen_spec.rb
> Valid move queen

- app/models/rook.rb
- db/schema.rb
- spec/factories.rb
- spec/models/rook_spec.rb
> Valid move rook

- app/models/bishop.rb
- spec/factories.rb
- spec/models/bishop_spec.rb
{Fixes #62]https://github.com/Peninsula-Pirate-Pawns/PPP-RubyRooks/issues/62
> valid_move and tests for bishop

- app/models/king.rb
- app/models/piece.rb
- spec/factories.rb
- spec/models/king_spec.rb
Fixes [#47] https://github.com/Peninsula-Pirate-Pawns/PPP-RubyRooks/issues/47
I added the valid_move? and some other methods that support the functionality of the method.
> Added valid_move? for king and supporting methods

- app/models/piece.rb
I like the methods you have written here. These are just the adjustments I thought would make it a bit more concise. Let me know what you think.
> Refactor support castling

- app/assets/stylesheets/master.scss
- app/controllers/pieces_controller.rb
- app/views/games/_board.html.erb
- app/views/games/show.html.erb
- spec/controllers/pieces_controller_spec.rb
1. Fixed tests
2. Cant drag pieces off board.
3. The replacing of every thing in the partial is due to the copy and paste to fix that problem I discussed on slack.
> Remove interstitial fix tests

- Gemfile
- Gemfile.lock
- config/cable.yml
- config/environments/production.rb
This adds the necessary configurations which allows ActionCable to work in our production environment.
> Prep actioncable for heroku

- app/controllers/pieces_controller.rb
- app/models/game.rb
- app/models/king.rb
- app/models/piece.rb
This doesn't finish the checkmate task, but it is much closer. The `threat_path` methods are all working as expected. We just need to troubleshoot a bit more for all the checkmate cases.
> Checkmate block

- app/assets/javascripts/channels/game.coffee.erb
- app/controllers/games_controller.rb
- app/views/games/index.html.erb
- app/views/games/reload.js.erb
- config/routes.rb
- spec/controllers/games_controller_spec.rb
This will reload the other persons screen when a player joins an available game.
> ActionCable for game#update_invited_user

- app/controllers/pieces_controller.rb
- app/helpers/games_helper.rb
- app/views/games/_board.html.erb
- app/views/games/_player_one.html.erb
- app/views/games/_player_two.html.erb
- spec/controllers/pieces_controller_spec.rb
- spec/features/castle_game_spec.rb
When  a player castles it now reloads the partials for both players.
> pieces#castle now works with ActionCable

- .rubocop.yml
- app/assets/javascripts/dashboard.coffee
- app/assets/stylesheets/1-Bootstrap.scss
- app/assets/stylesheets/bootstrap_overrides.scss
- app/assets/stylesheets/dashboard.scss
- app/assets/stylesheets/master.scss
- app/controllers/dashboard_controller.rb
- app/helpers/dashboard_helper.rb
- app/views/dashboard/index.html.erb
- app/views/games/index.html.erb
- app/views/layouts/application.html.erb
- config/routes.rb
- spec/controllers/dashboard_controller_spec.rb
This PR adds a dashboard for a signed-in user. It displays what shows on the main page now:
1 - Created Games
2 - Joined Games
3 - How many 'wins' the user has
I added a dashboard link that displays next to the 'sign out' button in the Navbar when a user is signed in.
I updated the colors of the 'new game' 'sign in' 'sign out' buttons in the NavBar as well to make them stand out. 
I plan to change the home page so that it prompts a user to sign in if they are not signed in and to list all games by most recently created and show if it is available to join or not. That will be a separate PR. Thanks!
> Add user dashboard

- .rubocop.yml
- app/assets/javascripts/dashboard.coffee
- app/assets/stylesheets/1-Bootstrap.scss
- app/assets/stylesheets/bootstrap_overrides.scss
- app/assets/stylesheets/dashboard.scss
- app/assets/stylesheets/master.scss
- app/controllers/dashboard_controller.rb
- app/helpers/dashboard_helper.rb
- app/views/dashboard/index.html.erb
- app/views/games/index.html.erb
- app/views/layouts/application.html.erb
- config/routes.rb
- spec/controllers/dashboard_controller_spec.rb
**Please review and merge PR #110 before reviewing/merging this one.**
This PR cleans up the home page a bit. 
-Added a box that renders if a user is not signed in that advises to sign in/sign up to start
-Created/Joined lists were moved to the user dashboard, so only available games are listed on game#show now
-Added some minimal styles to everything for visual pleasure. 
Thanks!
> Update game#show page

- .rubocop.yml
- app/assets/stylesheets/master.scss
- app/controllers/callbacks_controller.rb
- app/models/user.rb
- app/views/dashboard/index.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/games/index.html.erb
- app/views/games/new.html.erb
- app/views/layouts/application.html.erb
- config/initializers/devise.rb
- db/seeds.rb
-Update rubocop Line Length rules
-Style login, signup, forgot password, and new game pages
-Add font awesome for social icons
> Style login signup

- app/assets/stylesheets/bootstrap_overrides.scss
- app/views/layouts/application.html.erb
-Updates navbar styling for Bootstrap 4.3.1
> Update navbar styling
